language: swift

osx_image: xcode11
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 11 Pro Max"

script:
    - xcodebuild -scheme LPLibrary -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
